"""added sessionid

Revision ID: 398228269600
Revises: 7affe38061d
Create Date: 2016-04-04 22:49:08.267000

"""
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(
                os.path.dirname(os.path.abspath(__file__))))))

# revision identifiers, used by Alembic.
revision = '398228269600'
down_revision = '7affe38061d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'Appraisals', sa.Column('SessionId', sa.Text(), nullable=True))
    op.create_index(op.f('ix_Appraisals_SessionId'), 'Appraisals', ['SessionId'], unique=False)
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Appraisals_SessionId'), table_name='Appraisals')
    op.drop_column(u'Appraisals', 'SessionId')
    ### end Alembic commands ###
