"""Added SecretKey column

Revision ID: e1a6225b0595
Revises: 398228269600
Create Date: 2016-04-07 18:27:18.120000

"""
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(
                os.path.dirname(os.path.abspath(__file__))))))

# revision identifiers, used by Alembic.
revision = 'e1a6225b0595'
down_revision = '398228269600'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'Users', sa.Column('SecretKey', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'Users', 'SecretKey')
    ### end Alembic commands ###
